# Generated by Django 3.2.21 on 2023-09-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao_moeda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationcoin',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotacao_moeda.quotation', verbose_name='Cotação'),
        ),
    ]
