# Generated by Django 3.2.21 on 2023-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('acronym', models.CharField(max_length=4, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
            },
        ),
    ]
