# Generated by Django 3.2.21 on 2023-09-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='acronym',
            field=models.CharField(max_length=4, unique=True, verbose_name='Sigla'),
        ),
    ]
