# Generated by Django 3.2.21 on 2023-09-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0002_alter_coin_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='short_name',
            field=models.CharField(max_length=4, null=True, verbose_name='Nome curto'),
        ),
    ]
