# Generated by Django 3.2.21 on 2023-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0003_coin_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='short_name',
        ),
        migrations.AddField(
            model_name='coin',
            name='symbol',
            field=models.CharField(default=None, max_length=4, unique=True, verbose_name='Simbolo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='acronym',
            field=models.CharField(max_length=4, null=True, verbose_name='Sigla'),
        ),
    ]
